name: Arch Linux Build

on:
  push:
    branches:
      - HandBrake-SVT-AV1-Essential
  pull_request:
  schedule:
    - cron:  '30 7 * * 1,5'
  workflow_dispatch:

jobs:
  build:
    name: Build on Arch
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6

    - name: Cargo-C Toolchain Cache
      id: linux-cargo-c-toolchain
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/bin/cargo-capi
          ~/.cargo/bin/cargo-cbuild
          ~/.cargo/bin/cargo-cinstall
        key: linux-cargo-c-toolchain

    - name: Setup Cargo-C Toolchain
      if: steps.linux-cargo-c-toolchain.outputs.cache-hit != 'true'
      run: |
        cargo install cargo-c --force

    - name: Build HandBrake Arch Linux
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1.1.9

    - name: Upload HandBrake GUI
      uses: actions/upload-artifact@v6
      with:
        name: HandBrakeGUI
        path: ${{ steps.makepkg.outputs.pkgfile0 }}
    
    - name: Upload HandBrake CLI
      uses: actions/upload-artifact@v6
      with:
        name: HandBrakeCLI
        path: ${{ steps.makepkg.outputs.pkgfile1 }}


  deploy_nightly:
    name: Deploy Nightly Build
    runs-on: ubuntu-24.04
    needs: build
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v6
       
      - name: Download Artifacts - GUI Arch Linux
        uses: actions/download-artifact@v7
        with:
          name: HandBrakeGUI
          path: arch/
        
      - name: Download Artifacts - CLI Arch Linux
        uses: actions/download-artifact@v7
        with:
          name: HandBrakeCLI
          path: arch/

      # Generate Hashes
      - name: Generate SHA265 Hashes
        run: |
          cd arch
          sha256sum * > sha256.txt
          cp sha256.txt ../.github/workflows/
          cd ..
          cd .github/workflows/
          sed -e 's/  / | /' -i sha256.txt
          sed -e 's/^/| /'  -i sha256.txt
          sed -e 's/$/ |/' -i sha256.txt
          cat sha256.txt >> arch_rel_body.md
      
      # Publishing the Release
      - name: Remove the old Release
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 0
          delete_tag_pattern: "arch_essential_build"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "arch/*"
          name: "Essential Build for Arch Linux"
          bodyFile: .github/workflows/arch_rel_body.md
          prerelease: true
          replacesArtifacts: false
          allowUpdates: false
          tag: arch_essential_build
          token: ${{ secrets.GITHUB_TOKEN }}
